# Generated by Django 3.1 on 2020-08-26 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1000)),
                ('version', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConstraints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proximity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('endangerment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('water', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Model constraints',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=10000)),
                ('full_response', models.CharField(max_length=10000)),
                ('response', models.CharField(max_length=10000)),
                ('feedback', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zurichAPI.algorithms')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='zurichAPI.algorithms')),
            ],
        ),
        migrations.AddField(
            model_name='algorithms',
            name='parent_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zurichAPI.endpoints'),
        ),
    ]
