# Generated by Django 3.1 on 2020-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconstraints',
            name='algorithm',
            field=models.CharField(choices=[('ILP', 'ILP'), ('Other', 'Other')], default='ILP', max_length=9),
        ),
    ]
