# Generated by Django 3.1 on 2020-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0004_auto_20200826_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconstraints',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='endangerment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='proximity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='trees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='water',
            field=models.IntegerField(),
        ),
    ]
