# Generated by Django 3.1 on 2020-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0007_auto_20200827_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconstraints',
            name='area',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='budget',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='endangerment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='proximity',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='trees',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelconstraints',
            name='water',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
