# Generated by Django 3.1 on 2020-08-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0008_auto_20200827_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='feedback',
            new_name='inputs',
        ),
    ]
