# Generated by Django 3.1 on 2020-08-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0010_modelconstraints_requests_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelconstraints',
            old_name='requests_id',
            new_name='request_id',
        ),
    ]
