# Generated by Django 3.1 on 2020-08-27 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0011_auto_20200827_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconstraints',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
