# Generated by Django 3.1 on 2020-08-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zurichAPI', '0013_auto_20200827_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconstraints',
            name='request_id',
        ),
    ]
